apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: emr-eks-karpenter-ebs-sc
  namespace: emr-data-team-a
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  fsType: ext4

