apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: emr-eks-karpenter-ebs-sc
  namespace: emr-data-team-a
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  fsType: ext4
  tagSpecification_1: "pvcnamespace={{ .PVCNamespace }}"
  tagSpecification_2: "pvcname={{ .PVCName }}"  
  tagSpecification_3: "owner=emr-data-team-a"
  tagSpecification_4: "app=emr-containers"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-driver-pvc
  namespace: emr-data-team-a
spec:
  storageClassName: emr-eks-karpenter-ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
